# Generated by Django 4.1.5 on 2023-01-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_cruduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrudUser',
        ),
    ]
